// generated by prisma-to-graphql

export const models = {
    User: {
        id: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        createdAt: {
            isList: false,
            type: 'DateTime',
            isRelation: false,
        },
        updatedAt: {
            isList: false,
            type: 'DateTime',
            isRelation: false,
        },
        email: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        password: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        firstName: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        lastName: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        role: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        phoneNumber: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
    },
    Company: {
        id: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
        createdAt: {
            isList: false,
            type: 'DateTime',
            isRelation: false,
        },
        updatedAt: {
            isList: false,
            type: 'DateTime',
            isRelation: false,
        },
        name: {
            isList: false,
            type: 'String',
            isRelation: false,
        },
    },
} as const;