/* node:coverage disable */
/** This file is just types. */

import {
    type GraphqlBlockByType,
    type OperationType,
    type TopLevelNamedGraphqlBlock,
} from '../graphql-blocks/graphql-block.js';
import type {PrismaModel} from '../prisma-builders/dmmf-model.js';

/**
 * A generator used inside of the `prisma-to-graphql` Prisma generator to create resolvers and all
 * their needed types for each model.
 *
 * @category Prisma Generator
 */
export type ResolverBuilder = {
    type: OperationType;
    /** Callback that builds the resolver code. */
    build: (prismaModel: Readonly<PrismaModel>) => BuildOutput;
};

/**
 * Build outputs which will eventually be combined to form all the file outputs generated by
 * `prisma-to-graphql`.
 *
 * @category Prisma Generator
 */
export type BuildOutput = {
    topLevelNamedGraphqlBlocks: TopLevelNamedGraphqlBlock[];
    resolverGraphqlBlocks: GraphqlBlockByType[OperationType][];
};
